var flights = [ 
	// Вылетающие
	{
		flight: "ЮТ 904",
		status: "Отправлен",
		city: "Саратов",
		time: "20:00",
		expectedTime: "20:02",
		aviacompany: "Ютейр",
		terminal: "А",
	},
	{
		flight: "ДР 263",
		status: "Ожидается",
		city: "Калининград (Храброво)",
		time: "14:55",
		expectedTime: "14:55",
		aviacompany: "Победа",
		terminal: "А",
	},
	{
		flight: "РГ 221",
		status: "Опаздывает",
		city: "Ульяновск (Баратаевка)",
		time: "15:05",
		expectedTime: "15:30",
		aviacompany: "Опаздывает",
		terminal: "А",
	},
	{
		flight: "ZF 7743",
		status: "Ожидается",
		city: "Нягань (Камрань)",
		time: "15:10",
		expectedTime: "15:10",
		aviacompany: "Azur Air",
		terminal: "А",
	},
	{
		flight: "ФВ 5503",
		status: "Ожидается",
		city: "Сочи",
		time: "15:20",
		expectedTime: "15:20",
		aviacompany: "Россия",
		terminal: "А",
	},
		{
		flight: "ЮТ 557",
		status: "Отменен",
		city: "Махачкала",
		time: "18:00",
		expectedTime: "18:00",
		aviacompany: "Ютейр",
		terminal: "А",
	},
	// Прилетающие
	{
		flight: "ЮТ 172",
		status: "Прибыл",
		city: "Ульяновск (Баратаевка)",
		time: "13:20",
		expectedTime: "13:10",
		aviacompany: "Ютейр",
		terminal: "А",
	},	
	{
		flight: "ZF 7730",
		status: "Прибыл",
		city: "Гоа (Даболим)",
		time: "13:25",
		expectedTime: "13:20",
		aviacompany: "Azur Air",
		terminal: "А",
	},
	{
		flight: "ЮТ 4146",
		status: "Прибыл",
		city: "Киров",
		time: "13:30",
		expectedTime: "13:30",
		aviacompany: "Ютейр",
		terminal: "А",
	},
	{
		flight: "ФВ 6013",
		status: "Задерживается",
		city: "Санкт-Петербург (Пулково)",
		time: "13:30",
		expectedTime: "13:50",
		aviacompany: "Россия",
		terminal: "А",
	},
	{
		flight: "ЕК 2310",
		status: "Задерживается",
		city: "Киров",
		time: "13:40",
		expectedTime: "13:50",
		aviacompany: "Emirates",
		terminal: "А",
	},
	{
		flight: "ЮТ 445",
		status: "Задерживается",
		city: "Когалым",
		time: "13:40",
		expectedTime: "14:50",
		aviacompany: "Ютейр",
		terminal: "А",
	},
	{
		flight: "ЮТ 333",
		status: "Задерживается",
		city: "Нарьян-Мар",
		time: "15:00",
		expectedTime: "17:00",
		aviacompany: "Ютейр",
		terminal: "А",
	}
];